In [1]:
import pandas as pd
import numpy as np

from tqdm.notebook import tqdm

from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.neighbors import NearestNeighbors

%matplotlib inline

In [2]:
links = pd.read_csv('C:/Users/AAZam/Documents/Lern DS of Netology/Курс ML/12_Введение и классификация рекомендательных систем/links.csv')
movies = pd.read_csv('C:/Users/AAZam/Documents/Lern DS of Netology/Курс ML/12_Введение и классификация рекомендательных систем/movies.csv')
ratings = pd.read_csv('C:/Users/AAZam/Documents/Lern DS of Netology/Курс ML/12_Введение и классификация рекомендательных систем/ratings.csv')
tags = pd.read_csv('C:/Users/AAZam/Documents/Lern DS of Netology/Курс ML/12_Введение и классификация рекомендательных систем/tags.csv')

In [3]:
movies.head(10)

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   
5        6                         Heat (1995)   
6        7                      Sabrina (1995)   
7        8                 Tom and Huck (1995)   
8        9                 Sudden Death (1995)   
9       10                    GoldenEye (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy  
5                        Action|Crime|Thriller  
6                               Comedy|Romance  
7                           Adventure|Children  
8                                       Action  
9                    Action|Adventure|Thriller

In [4]:
movies.genres.values

array(['Adventure|Animation|Children|Comedy|Fantasy',
       'Adventure|Children|Fantasy', 'Comedy|Romance', ..., 'Drama',
       'Action|Animation', 'Comedy'], dtype=object)

In [5]:
def change_string(s):
    return ' '.join(s.replace(' ', '').replace('-', '').split('|'))

In [6]:
movie_genres = [change_string(g) for g in movies.genres.values]

In [7]:
movies.info

<bound method DataFrame.info of       movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Dra

In [8]:
movie_genres[:5]

['Adventure Animation Children Comedy Fantasy',
 'Adventure Children Fantasy',
 'Comedy Romance',
 'Comedy Drama Romance',
 'Comedy']

In [9]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(movie_genres)

In [10]:
X_train_counts.shape

(9742, 20)

In [11]:
X_train_counts.todense()

matrix([[0, 1, 1, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [1, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [13]:
X_train_tfidf.todense()

matrix([[0.        , 0.41684567, 0.51622547, ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.51236121, 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.57860574, 0.        , 0.81560738, ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]])

In [14]:
neigh = NearestNeighbors(n_neighbors=7, n_jobs=-1, metric='euclidean') 
neigh.fit(X_train_tfidf)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='euclidean',
                 metric_params=None, n_jobs=-1, n_neighbors=7, p=2, radius=1.0)

In [15]:
test = change_string("Adventure|Comedy|Fantasy|Crime")

predict = count_vect.transform([test])
X_tfidf2 = tfidf_transformer.transform(predict)

res = neigh.kneighbors(X_tfidf2, return_distance=True)

In [16]:
res

(array([[0.42079615, 0.53300564, 0.54288608, 0.54288608, 0.54288608,
         0.54288608, 0.54288608]]),
 array([[6774, 9096, 5636, 6723, 3376, 7496, 9717]], dtype=int64))

In [17]:
movies.iloc[res[1][0]]

movieId                                              title  \
6774    60074                                     Hancock (2008)   
9096   143559                                L.A. Slasher (2015)   
5636    27368  Asterix & Obelix: Mission Cleopatra (Astérix &...   
6723    58972                                Nim's Island (2008)   
3376     4591                             Erik the Viking (1989)   
7496    82854                          Gulliver's Travels (2010)   
9717   188833              The Man Who Killed Don Quixote (2018)   

                                     genres  
6774  Action|Adventure|Comedy|Crime|Fantasy  
9096                   Comedy|Crime|Fantasy  
5636               Adventure|Comedy|Fantasy  
6723               Adventure|Comedy|Fantasy  
3376               Adventure|Comedy|Fantasy  
7496               Adventure|Comedy|Fantasy  
9717               Adventure|Comedy|Fantasy

In [18]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [19]:
tags.head()

userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [20]:
movies_with_tags = movies.join(tags.set_index('movieId'), on='movieId')

In [21]:
movies_with_tags.head()

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        2    Jumanji (1995)                   Adventure|Children|Fantasy   
1        2    Jumanji (1995)                   Adventure|Children|Fantasy   

   userId               tag     timestamp  
0   336.0             pixar  1.139046e+09  
0   474.0             pixar  1.137207e+09  
0   567.0               fun  1.525286e+09  
1    62.0           fantasy  1.528844e+09  
1    62.0  magic board game  1.528844e+09

In [22]:
movies_with_tags[movies_with_tags.title == 'Toy Story (1995)']

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   

   userId    tag     timestamp  
0   336.0  pixar  1.139046e+09  
0   474.0  pixar  1.137207e+09  
0   567.0    fun  1.525286e+09

In [23]:
movies_with_tags.tag.unique()

array(['pixar', 'fun', 'fantasy', ..., 'star wars', 'gintama', 'remaster'],
      dtype=object)

In [24]:
movies_with_tags.tag.unique().shape

(1590,)

In [25]:
movies_with_tags.dropna(inplace=True)

In [26]:
movies_with_tags.title.unique().shape

(1572,)

In [27]:
movies_with_tags_groupby = movies_with_tags.groupby('title')
movies_with_tags_groupby.head()

movieId                           title  \
0           1                Toy Story (1995)   
0           1                Toy Story (1995)   
0           1                Toy Story (1995)   
1           2                  Jumanji (1995)   
1           2                  Jumanji (1995)   
...       ...                             ...   
9710   187595  Solo: A Star Wars Story (2018)   
9732   193565       Gintama: The Movie (2010)   
9732   193565       Gintama: The Movie (2010)   
9732   193565       Gintama: The Movie (2010)   
9732   193565       Gintama: The Movie (2010)   

                                           genres  userId               tag  \
0     Adventure|Animation|Children|Comedy|Fantasy   336.0             pixar   
0     Adventure|Animation|Children|Comedy|Fantasy   474.0             pixar   
0     Adventure|Animation|Children|Comedy|Fantasy   567.0               fun   
1                      Adventure|Children|Fantasy    62.0           fantasy   
1                      Adventure|Children|Fantasy    62.0  magic board game   
...                                           ...     ...               ...   
9710             Action|Adventure|Children|Sci-Fi    62.0         star wars   
9732               Action|Animation|Comedy|Sci-Fi   184.0             anime   
9732               Action|Animation|Comedy|Sci-Fi   184.0            comedy   
9732               Action|Animation|Comedy|Sci-Fi   184.0           gintama   
9732               Action|Animation|Comedy|Sci-Fi   184.0          remaster   

         timestamp  
0     1.139046e+09  
0     1.137207e+09  
0     1.525286e+09  
1     1.528844e+09  
1     1.528844e+09  
...            ...  
9710  1.528935e+09  
9732  1.537099e+09  
9732  1.537099e+09  
9732  1.537099e+09  
9732  1.537099e+09  

[2851 rows x 6 columns]

In [28]:
tag_strings = []
movi = []

for movie, group in tqdm(movies_with_tags.groupby('title')):
    tag_strings.append(' '.join([str(s).replace(' ', '').replace('-', '') for s in group.tag.values]))
    movi.append(movie)

In [29]:
tag_strings[:5]

['artistic Funny humorous inspiring intelligent quirky romance ZooeyDeschanel',
 'lawyers',
 'creepy suspense',
 'Shakespearesortof',
 'dogs remake']

In [30]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(tag_strings)

In [31]:
X_train_counts.todense()

matrix([[0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
X_train_counts.shape

(1572, 1472)

In [33]:
len(movi)

1572

In [34]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [35]:
neigh = NearestNeighbors(n_neighbors=10, n_jobs=-1, metric='manhattan') 
neigh.fit(X_train_tfidf)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='manhattan',
                 metric_params=None, n_jobs=-1, n_neighbors=10, p=2,
                 radius=1.0)

In [36]:
for i in range(len(movi)):
    if 'Magnolia (1999)' == movi[i]:
        print(i)

822


In [37]:
tag_strings[822]

'L.A.'

In [38]:
test = change_string('pixar pixar fun')

predict = count_vect.transform([test])
X_tfidf2 = tfidf_transformer.transform(predict)

res = neigh.kneighbors(X_tfidf2, return_distance=True)

In [39]:
res

(array([[0., 0., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([[661, 822, 947, 955, 954, 953, 951, 950, 949, 959]], dtype=int64))

In [40]:
for i in res[1][0]:
    print(movi[i])

In a Lonely Place (1950)
Magnolia (1999)
Neon Genesis Evangelion: Death & Rebirth (Shin seiki Evangelion Gekijô-ban: Shito shinsei) (1997)
Night and Day (1946)
Nicholas Nickleby (2002)
Niagara (1953)
Never Been Kissed (1999)
Network (1976)
Net, The (1995)
Night of the Hunter, The (1955)


# Домашняя работа

In [41]:
movies_with_tags.head()

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        2    Jumanji (1995)                   Adventure|Children|Fantasy   
1        2    Jumanji (1995)                   Adventure|Children|Fantasy   

   userId               tag     timestamp  
0   336.0             pixar  1.139046e+09  
0   474.0             pixar  1.137207e+09  
0   567.0               fun  1.525286e+09  
1    62.0           fantasy  1.528844e+09  
1    62.0  magic board game  1.528844e+09

In [67]:
tag_genres_strings = []
movies = []

for movie, group in tqdm(movies_with_tags.groupby('title')):
#     print(movie)
#     print(group)
#     print(group.genres.values[0])
    tag_genres_strings.append(' '.join([str(s).replace(' ', '').replace('-', '') for s in group.tag.values]) + ' ' + ' '.join(group.genres.values[0].replace(' ', '').replace('-', '').split('|')))
#     tag_genres_strings.append(' '.join(group.genres.values[0].replace(' ', '').replace('-', '').split('|')))
    movies.append(movie)

In [68]:
tag_genres_strings[:5]

['artistic Funny humorous inspiring intelligent quirky romance ZooeyDeschanel Comedy Drama Romance',
 'lawyers Drama Thriller',
 'creepy suspense Thriller',
 'Shakespearesortof Comedy Romance',
 'dogs remake Adventure Children Comedy']

In [70]:
len(tag_genres_strings)

1572

In [72]:
len(movies)

1572

In [80]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(tag_genres_strings)

In [81]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [83]:
X_train_tfidf.shape

(1572, 1475)

In [82]:
neigh = NearestNeighbors(n_neighbors=10, n_jobs=-1, metric='manhattan') 
neigh.fit(X_train_tfidf)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='manhattan',
                 metric_params=None, n_jobs=-1, n_neighbors=10, p=2,
                 radius=1.0)

In [75]:
for i in range(len(movies)):
    if 'Jumanji (1995)' == movi[i]:
        print(i)

712


In [76]:
tag_genres_strings[712]

'fantasy magicboardgame RobinWilliams game Adventure Children Fantasy'

In [84]:
test = change_string('fantasy magicboardgame RobinWilliams game Adventure Children Fantasy')

predict = count_vect.transform([test])
X_tfidf2 = tfidf_transformer.transform(predict)

res = neigh.kneighbors(X_tfidf2, return_distance=True)

In [85]:
res

(array([[1.        , 1.        , 1.        , 1.12968725, 1.18066215,
         1.18066215, 1.18066215, 1.18066215, 1.18066215, 1.18066215]]),
 array([[  36,  822,  686,  336,  176,  591, 1264,  700,  788,  622]],
       dtype=int64))

In [86]:
for i in res[1][0]:
    print(movies[i])

Airheads (1994)
Magnolia (1999)
Invincible Iron Man, The (2007)
Dead Poets Society (1989)
Blue Car (2002)
Heaven (2002)
Sling Blade (1996)
Jane Eyre (1970)
Little Women (1994)
House of Sand and Fog (2003)
