### Строим модели линейной и логистической регрессии

In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.datasets.samples_generator import make_regression
from sklearn import datasets 
import pylab
from scipy import stats
import math

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data[0:100]
x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
y = iris.target[0:100]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
def gradient_desend_4(alfa, x, y, numIterations):
    """
    Функция реализует алгоритм градиентного спуска. На каждом шаге вводится значение потерь
    """
    
    m = x.shape[0] #100
    theta = np.ones(len(x[0])) # [...] Веса модели
    x_transpose = x.transpose() #Транспонированная матрица х
        
    for iter in range(0, numIterations):
        
        hypothesis = 1 / (1 + math.e**(-1*np.dot(x, theta.T))) # предсказание y
        loss = hypothesis - y
        
        gradient = np.dot(x_transpose, loss) / m # Градиент = (транспонированная матрица х * на веса) / на количество данных
        
        J = (-y * np.log(hypothesis)) - ((1 - y) * np.log(1 - hypothesis)) # Логарифмическое уравнение правдоподобия
        J = np.mean(J)
        J_1 = np.sum(loss**2)/(2*m) # Функция потерь LOSS FUNCTIONS (MSE)
       
        theta = theta - alfa * gradient # Обновляем значение theta
       
    return theta

In [10]:
theta = gradient_desend_4(0.1, x, y, 100)
theta

array([-0.61584446, -0.69271364,  1.61334803,  1.36577309])

In [11]:
prediction = 1 / (1 + math.e**(-1*np.dot(x, theta)))

In [12]:
pred_y = np.where(prediction >= .5, 1, 0)

In [13]:
print("Количество точных предсказаний:", np.sum(y == pred_y))

Количество точных предсказаний: 100


In [15]:
def gradient_desend_5(alfa, x, y, numIterations):
    """
    Функция реализует алгоритм Nesterov Accelerated Gradient
    """
    
    m = x.shape[0] #100
    theta = np.ones(len(x[0])) # [...] Веса модели
    change_theta = np.zeros(len(x[0])) # [...] Веса модели
    x_transpose = x.transpose() #Транспонированная матрица х
        
    for iter in range(0, numIterations):
        
        hypothesis = 1 / (1 + math.e**(-1*np.dot(x, theta.T))) # предсказание y
        loss = hypothesis - y
        
        gradient = np.dot(x_transpose, loss) / m # Градиент = (транспонированная матрица х * на веса) / на количество данных
        
        J = (-y * np.log(hypothesis)) - ((1 - y) * np.log(1 - hypothesis)) # Логарифмическое уравнение правдоподобия
        J = np.mean(J)
        J_1 = np.sum(loss**2)/(2*m) # Функция потерь LOSS FUNCTIONS (MSE)
        
        old_theta = theta
        theta = theta - (0.9*change_theta + alfa * gradient) # Обновляем значение theta
        change_theta += (old_theta - theta)
        
    return theta

In [16]:
theta = gradient_desend_5(0.1, x, y, 100)
theta

C:\Users\AAZam\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in power
  del sys.path[0]
C:\Users\AAZam\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: divide by zero encountered in log
C:\Users\AAZam\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in multiply


array([-1.49103105e+27, -1.08650958e+27, -3.08673042e+26, -2.14261142e+25])